baseURL: "https://dutrend.com"
languageCode: en-us
title: Du Trend
theme: PaperMod
paginate: 6

params:
  env: production
  homeInfoParams:
    Content: "Domain for sale. Please contact us via email: nhagiaodichfx@gmail.com. Thank you!"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/nhagiaodich_com"
    - name: tiktok
      url: "https://tiktok.com/@nhagiaodich_com"
    - name: facebook
      url: "https://www.facebook.com/nhagiaodichcom"
    - name: youtube
      url: "https://www.youtube.com/@nhagiaodich_com"
    - name: email
      url: "mailto:nhagiaodichfx@gmail.com"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
